"""Teaching methodology — Feynman Technique + Four-Part Output templates.

Provides structured formatting for assembling the complete teaching response
from the four parts generated by LangGraph nodes.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# Section separator with emoji markers for Chainlit rendering
SECTION_SEPARATOR = "\n\n---\n\n"

# Part labels (displayed to the student as section headers)
PART_LABELS = {
    "core": "## ① Core Process · 核心流程讲解",
    "example": "## ② Interspersed Examples · 示例展开",
    "math": "## ③ Math & Notation · 数学与符号",
    "summary": "## ④ Summary · 总结提炼",
}


class TeachingMethodology:
    """Applies the four-part Feynman teaching structure to generated content.

    This is a presentation-layer module that assembles raw LLM outputs
    into the canonical teaching format with section headers and transitions.
    """

    @staticmethod
    def assemble_full_response(
        core_explanation: str = "",
        examples: str = "",
        math_notation: str = "",
        section_summary: str = "",
    ) -> str:
        """Assemble all four parts into a complete teaching response.

        Args:
            core_explanation: Part ① — Core Process.
            examples: Part ② — Interspersed Examples.
            math_notation: Part ③ — Math & Notation.
            section_summary: Part ④ — Summary.

        Returns:
            Formatted markdown string with all sections.
        """
        parts = []

        if core_explanation:
            parts.append(f"{PART_LABELS['core']}\n\n{core_explanation}")

        if examples:
            parts.append(f"{PART_LABELS['example']}\n\n{examples}")

        if math_notation:
            parts.append(f"{PART_LABELS['math']}\n\n{math_notation}")

        if section_summary:
            parts.append(f"{PART_LABELS['summary']}\n\n{section_summary}")

        full_response = SECTION_SEPARATOR.join(parts)

        logger.info(
            "Assembled full response: core=%d, example=%d, math=%d, summary=%d → %d chars total",
            len(core_explanation), len(examples), len(math_notation),
            len(section_summary), len(full_response)
        )

        return full_response

    @staticmethod
    def assemble_partial_response(
        core_explanation: str = "",
        examples: Optional[str] = None,
        math_notation: Optional[str] = None,
        section_summary: Optional[str] = None,
    ) -> str:
        """Assemble a subset of parts (for streaming or incomplete responses).

        Only includes parts that are not None. Empty strings are included.
        None values are skipped.
        """
        parts = []

        if core_explanation:
            parts.append(f"{PART_LABELS['core']}\n\n{core_explanation}")

        if examples is not None:
            parts.append(f"{PART_LABELS['example']}\n\n{examples}")

        if math_notation is not None:
            parts.append(f"{PART_LABELS['math']}\n\n{math_notation}")

        if section_summary is not None:
            parts.append(f"{PART_LABELS['summary']}\n\n{section_summary}")

        return SECTION_SEPARATOR.join(parts) if parts else ""

    @staticmethod
    def get_teaching_principles() -> str:
        """Return the core teaching principles for reference."""
        return """
## Feynman Teaching Principles

1. **Intuition First** — Start with what the student can visualize,
   then formalize. Never define before explaining WHY.

2. **Plain Language** — If you can't explain it to a bright
   high-schooler, you don't understand it well enough.

3. **Concrete Before Abstract** — Every abstract concept needs
   a concrete anchor (example, analogy, or diagram).

4. **Build Bridges** — Connect new knowledge to what the student
   already knows. Learning is linking.

5. **Check Understanding** — Ask questions to verify comprehension.
   The student should be able to re-explain in their own words.
""".strip()
