"""Teaching methodology — Feynman Technique + Four-Part Output templates.

Provides structured formatting for assembling the complete teaching response
from the four parts generated by LangGraph nodes.
"""

import logging
import re
from typing import Optional

logger = logging.getLogger(__name__)

# Section separator with emoji markers for Chainlit rendering
SECTION_SEPARATOR = "\n\n---\n\n"

# Part labels (displayed to the student as section headers)
PART_LABELS = {
    "core": "## ① Core Process · 核心流程讲解",
    "example": "## ② Interspersed Examples · 示例展开",
    "math": "## ③ Math & Notation · 数学与符号",
    "summary": "## ④ Summary · 总结提炼",
}

# Variants the LLM tends to emit at the start of each part (because the
# generation prompts instruct it to "write Part ②: **Interspersed
# Examples（示例展开）**"). These get stripped before we prepend our
# canonical PART_LABELS so the student doesn't see the header twice.
# Detection is line based and tolerant of markdown emphasis, the circled
# ①②③④ glyph, "Part N:", full-width parens, and the chinese subtitle.
_PART_HEADER_KEYWORDS: dict[str, tuple[str, str]] = {
    "core":     ("Core Process",          "核心流程"),
    "example":  ("Interspersed Examples", "示例展开"),
    "math":     ("Math & Notation",       "数学与符号"),
    "summary":  ("Summary",               "总结提炼"),
}


def _strip_duplicate_part_header(text: str, part_key: str) -> str:
    """Remove the LLM-emitted section header lines from anywhere in ``text``.

    The teaching prompts ask the model to "write Part ②: …" which the model
    often echoes verbatim. Since ``assemble_full_response`` prepends its own
    canonical ``PART_LABELS`` header, an echoed line would otherwise appear
    twice in the rendered message.

    Strategy (full-scan, NOT lead-line only): the model sometimes writes a
    one-line preamble (e.g. "好的，现在我们来写 **② Interspersed Examples
    （示例展开）**。我会…") and only AFTER that emits a bare header line
    ("② Interspersed Examples（示例展开）"). A lead-only stripper stops at
    the preamble and misses the bare header. Here we walk EVERY line and
    drop any line that, on its own, looks like a part header:

      - short (≤80 chars after stripping noise)
      - dominated by the part's english title / chinese subtitle tokens
        (>= 2 title tokens hit, OR full english title present, OR
        chinese subtitle present), with at most 1 body word (≠ title tokens)
      - OR a "Part N:" decorative prefix-only line
      - NOT inside a ``$$…$$`` / ``$…$`` math block
      - NOT an Example/Step/numbered-list item ("Example 1:", "Step 2:",
        "1. ", "1 Gather …") — those are body content the student needs.

    The preamble line (containing many body words) is kept because it carries
    useful transitional voice; only bare header lines are removed.
    """
    en_title, cn_title = _PART_HEADER_KEYWORDS.get(part_key, ("", ""))
    if not en_title:
        return text.strip()

    # Tokenize the canonical english title once for the word-overlap test.
    header_toks = set(re.split(r"\s+", en_title.lower().replace("&", " "))) | set(en_title.lower().split())
    header_toks -= {"", "&", "and"}
    cn_toks = {cn_title}

    # Decode text into segments, protecting math blocks so we never strip a
    # header-looking fragment that is actually inside a math expression.
    math_spans: list[tuple[int, int]] = []
    for m in re.finditer(r"\$\$.+?\$\$|\$[^$]+?\$", text, re.DOTALL):
        math_spans.append((m.start(), m.end()))

    def _in_math(pos: int) -> bool:
        return any(s <= pos < e for s, e in math_spans)

    out_lines: list[str] = []
    pos = 0
    for line in text.split("\n"):
        line_end = pos + len(line)
        stripped = line.strip()
        if stripped and not _in_math(pos):
            # Strip markdown emphasis, circled digits, separators once.
            norm = re.sub(r"[#*`_>:]+", "", stripped)
            norm = norm.replace("①", "").replace("②", "").replace("③", "").replace("④", "")
            norm_alpha = re.sub(r"[·•：:.\-—\s（）()【】\[\]]+", " ", norm).strip()
            tok_str = re.sub(r"\s+", " ", norm_alpha).lower().strip()
            tokens = set(tok_str.split()) if tok_str else set()
            body_toks = {t for t in tokens if t and t not in header_toks and t not in cn_toks and len(t) > 1}
            en_hit = sum(1 for t in header_toks if t in tokens)
            mentions_title = (en_hit >= 2) or (en_title.lower() in tok_str) or (cn_title in norm)
            is_header_line = (
                mentions_title
                and len(body_toks) <= 1
                and len(norm_alpha) <= 80
            )
            is_part_prefix_only = bool(re.fullmatch(r"[Pp]art\s*[①②③④1-4]\s*:?\s*", norm_alpha))
            # Reject lines that look like Example/Step/numbered-list content
            # so we never drop "Example 1: …" — those are real body even when
            # they happen to mention the title words.
            is_list_item = bool(re.match(
                r"^(?:Example\s+\d+|Step\s+\d+|\d+\.\s|例\s*\d+|case\s+\d+|Case\s+\d+)",
                stripped,
                re.IGNORECASE,
            ))
            if (is_header_line or is_part_prefix_only) and not is_list_item:
                pos = line_end + 1  # skip this line + the newline
                continue
        out_lines.append(line)
        pos = line_end + 1

    # Collapse runs of blank lines that header-removal may have produced.
    cleaned = "\n".join(out_lines)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()

# ---------------------------------------------------------------------------
# LaTeX normalization — post-process LLM output for KaTeX rendering
# ---------------------------------------------------------------------------
# Chainlit renders math via KaTeX, which requires $...$ / $$...$$ delimiters.
# LLMs often emit math wrapped in spaced parentheses like "( X_{ij} )" or use
# \(...\) / \[...\] delimiters. These patterns render as plain text. This
# function converts them to $...$ / $$...$$ so KaTeX picks them up.

_PAREN_MATH_RE = re.compile(r"\(\s+([^()]{1,80}?)\s+\)")
_INLINE_DELIM_RE = re.compile(r"\\\((.+?)\\\)", re.DOTALL)
_DISPLAY_DELIM_RE = re.compile(r"\\\[(.+?)\\\]", re.DOTALL)
_EXISTING_MATH_RE = re.compile(r"\$\$.+?\$\$|\$[^$]+?\$", re.DOTALL)


def _looks_like_math(content: str) -> bool:
    """Heuristic: does this short string look like a math expression?"""
    content = content.strip()
    if not content:
        return False
    if any(c in content for c in "_^{}\\"):
        return True
    if re.search(r"\\[a-zA-Z]+", content):
        return True
    if len(content) == 1 and content.isalpha() and content.isascii():
        return True
    return False


def normalize_latex(text: str) -> str:
    """Post-process LLM output so math is wrapped in KaTeX delimiters.

    Handles:
    - ``\\( ... \\)`` → ``$...$``
    - ``\\[ ... \\]`` → ``$$...$$``
    - ``( X_{ij} )``  → ``$X_{ij}$``  (spaced parens around math-like content)
    """
    # Step 1: Convert \(...\) and \[...\]
    text = _INLINE_DELIM_RE.sub(lambda m: f"${m.group(1).strip()}$", text)
    text = _DISPLAY_DELIM_RE.sub(lambda m: f"$${m.group(1).strip()}$$", text)

    # Step 2: Protect already-wrapped $...$ and $$...$$
    placeholders: dict[str, str] = {}

    def _protect(m: "re.Match[str]") -> str:
        key = f"__MATH_PROTECT_{len(placeholders)}__"
        placeholders[key] = m.group(0)
        return key

    text = _EXISTING_MATH_RE.sub(_protect, text, count=0)

    # Step 3: Wrap bare math in spaced parentheses → $...$
    def _wrap_paren_math(m: "re.Match[str]") -> str:
        content = m.group(1).strip()
        if _looks_like_math(content):
            return f"${content}$"
        return m.group(0)

    text = _PAREN_MATH_RE.sub(_wrap_paren_math, text)

    # Step 4: Restore protected math
    for key, val in placeholders.items():
        text = text.replace(key, val)

    return text


class TeachingMethodology:
    """Applies the four-part Feynman teaching structure to generated content.

    This is a presentation-layer module that assembles raw LLM outputs
    into the canonical teaching format with section headers and transitions.
    """

    @staticmethod
    def assemble_full_response(
        core_explanation: str = "",
        examples: str = "",
        math_notation: str = "",
        section_summary: str = "",
    ) -> str:
        """Assemble all four parts into a complete teaching response.

        Args:
            core_explanation: Part ① — Core Process.
            examples: Part ② — Interspersed Examples.
            math_notation: Part ③ — Math & Notation.
            section_summary: Part ④ — Summary.

        Returns:
            Formatted markdown string with all sections.
        """
        parts = []

        if core_explanation:
            cleaned = _strip_duplicate_part_header(core_explanation, "core")
            parts.append(f"{PART_LABELS['core']}\n\n{normalize_latex(cleaned)}")

        if examples:
            cleaned = _strip_duplicate_part_header(examples, "example")
            parts.append(f"{PART_LABELS['example']}\n\n{normalize_latex(cleaned)}")

        if math_notation:
            cleaned = _strip_duplicate_part_header(math_notation, "math")
            parts.append(f"{PART_LABELS['math']}\n\n{normalize_latex(cleaned)}")

        if section_summary:
            cleaned = _strip_duplicate_part_header(section_summary, "summary")
            parts.append(f"{PART_LABELS['summary']}\n\n{normalize_latex(cleaned)}")

        full_response = SECTION_SEPARATOR.join(parts)

        logger.info(
            "Assembled full response: core=%d, example=%d, math=%d, summary=%d → %d chars total",
            len(core_explanation), len(examples), len(math_notation),
            len(section_summary), len(full_response)
        )

        return full_response

    @staticmethod
    def assemble_partial_response(
        core_explanation: str = "",
        examples: Optional[str] = None,
        math_notation: Optional[str] = None,
        section_summary: Optional[str] = None,
    ) -> str:
        """Assemble a subset of parts (for streaming or incomplete responses).

        Only includes parts that are not None. Empty strings are included.
        None values are skipped.
        """
        parts = []

        if core_explanation:
            cleaned = _strip_duplicate_part_header(core_explanation, "core")
            parts.append(f"{PART_LABELS['core']}\n\n{normalize_latex(cleaned)}")

        if examples is not None:
            cleaned = _strip_duplicate_part_header(examples, "example")
            parts.append(f"{PART_LABELS['example']}\n\n{normalize_latex(cleaned)}")

        if math_notation is not None:
            cleaned = _strip_duplicate_part_header(math_notation, "math")
            parts.append(f"{PART_LABELS['math']}\n\n{normalize_latex(cleaned)}")

        if section_summary is not None:
            cleaned = _strip_duplicate_part_header(section_summary, "summary")
            parts.append(f"{PART_LABELS['summary']}\n\n{normalize_latex(cleaned)}")

        return SECTION_SEPARATOR.join(parts) if parts else ""

    @staticmethod
    def get_teaching_principles() -> str:
        """Return the core teaching principles for reference."""
        return """
## Feynman Teaching Principles

1. **Intuition First** — Start with what the student can visualize,
   then formalize. Never define before explaining WHY.

2. **Plain Language** — If you can't explain it to a bright
   high-schooler, you don't understand it well enough.

3. **Concrete Before Abstract** — Every abstract concept needs
   a concrete anchor (example, analogy, or diagram).

4. **Build Bridges** — Connect new knowledge to what the student
   already knows. Learning is linking.

5. **Check Understanding** — Ask questions to verify comprehension.
   The student should be able to re-explain in their own words.
""".strip()
