"""Teaching methodology — Feynman Technique + Four-Part Output templates.

Provides structured formatting for assembling the complete teaching response
from the four parts generated by LangGraph nodes.
"""

import logging
import re
from typing import Optional

logger = logging.getLogger(__name__)

# Section separator with emoji markers for Chainlit rendering
SECTION_SEPARATOR = "\n\n---\n\n"

# Part labels (displayed to the student as section headers)
PART_LABELS = {
    "core": "## ① Core Process · 核心流程讲解",
    "example": "## ② Interspersed Examples · 示例展开",
    "math": "## ③ Math & Notation · 数学与符号",
    "summary": "## ④ Summary · 总结提炼",
}

# ---------------------------------------------------------------------------
# LaTeX normalization — post-process LLM output for KaTeX rendering
# ---------------------------------------------------------------------------
# Chainlit renders math via KaTeX, which requires $...$ / $$...$$ delimiters.
# LLMs often emit math wrapped in spaced parentheses like "( X_{ij} )" or use
# \(...\) / \[...\] delimiters. These patterns render as plain text. This
# function converts them to $...$ / $$...$$ so KaTeX picks them up.

_PAREN_MATH_RE = re.compile(r"\(\s+([^()]{1,80}?)\s+\)")
_INLINE_DELIM_RE = re.compile(r"\\\((.+?)\\\)", re.DOTALL)
_DISPLAY_DELIM_RE = re.compile(r"\\\[(.+?)\\\]", re.DOTALL)
_EXISTING_MATH_RE = re.compile(r"\$\$.+?\$\$|\$[^$]+?\$", re.DOTALL)


def _looks_like_math(content: str) -> bool:
    """Heuristic: does this short string look like a math expression?"""
    content = content.strip()
    if not content:
        return False
    if any(c in content for c in "_^{}\\"):
        return True
    if re.search(r"\\[a-zA-Z]+", content):
        return True
    if len(content) == 1 and content.isalpha() and content.isascii():
        return True
    return False


def normalize_latex(text: str) -> str:
    """Post-process LLM output so math is wrapped in KaTeX delimiters.

    Handles:
    - ``\\( ... \\)`` → ``$...$``
    - ``\\[ ... \\]`` → ``$$...$$``
    - ``( X_{ij} )``  → ``$X_{ij}$``  (spaced parens around math-like content)
    """
    # Step 1: Convert \(...\) and \[...\]
    text = _INLINE_DELIM_RE.sub(lambda m: f"${m.group(1).strip()}$", text)
    text = _DISPLAY_DELIM_RE.sub(lambda m: f"$${m.group(1).strip()}$$", text)

    # Step 2: Protect already-wrapped $...$ and $$...$$
    placeholders: dict[str, str] = {}

    def _protect(m: "re.Match[str]") -> str:
        key = f"__MATH_PROTECT_{len(placeholders)}__"
        placeholders[key] = m.group(0)
        return key

    text = _EXISTING_MATH_RE.sub(_protect, text, count=0)

    # Step 3: Wrap bare math in spaced parentheses → $...$
    def _wrap_paren_math(m: "re.Match[str]") -> str:
        content = m.group(1).strip()
        if _looks_like_math(content):
            return f"${content}$"
        return m.group(0)

    text = _PAREN_MATH_RE.sub(_wrap_paren_math, text)

    # Step 4: Restore protected math
    for key, val in placeholders.items():
        text = text.replace(key, val)

    return text


class TeachingMethodology:
    """Applies the four-part Feynman teaching structure to generated content.

    This is a presentation-layer module that assembles raw LLM outputs
    into the canonical teaching format with section headers and transitions.
    """

    @staticmethod
    def assemble_full_response(
        core_explanation: str = "",
        examples: str = "",
        math_notation: str = "",
        section_summary: str = "",
    ) -> str:
        """Assemble all four parts into a complete teaching response.

        Args:
            core_explanation: Part ① — Core Process.
            examples: Part ② — Interspersed Examples.
            math_notation: Part ③ — Math & Notation.
            section_summary: Part ④ — Summary.

        Returns:
            Formatted markdown string with all sections.
        """
        parts = []

        if core_explanation:
            parts.append(f"{PART_LABELS['core']}\n\n{normalize_latex(core_explanation)}")

        if examples:
            parts.append(f"{PART_LABELS['example']}\n\n{normalize_latex(examples)}")

        if math_notation:
            parts.append(f"{PART_LABELS['math']}\n\n{normalize_latex(math_notation)}")

        if section_summary:
            parts.append(f"{PART_LABELS['summary']}\n\n{normalize_latex(section_summary)}")

        full_response = SECTION_SEPARATOR.join(parts)

        logger.info(
            "Assembled full response: core=%d, example=%d, math=%d, summary=%d → %d chars total",
            len(core_explanation), len(examples), len(math_notation),
            len(section_summary), len(full_response)
        )

        return full_response

    @staticmethod
    def assemble_partial_response(
        core_explanation: str = "",
        examples: Optional[str] = None,
        math_notation: Optional[str] = None,
        section_summary: Optional[str] = None,
    ) -> str:
        """Assemble a subset of parts (for streaming or incomplete responses).

        Only includes parts that are not None. Empty strings are included.
        None values are skipped.
        """
        parts = []

        if core_explanation:
            parts.append(f"{PART_LABELS['core']}\n\n{normalize_latex(core_explanation)}")

        if examples is not None:
            parts.append(f"{PART_LABELS['example']}\n\n{normalize_latex(examples)}")

        if math_notation is not None:
            parts.append(f"{PART_LABELS['math']}\n\n{normalize_latex(math_notation)}")

        if section_summary is not None:
            parts.append(f"{PART_LABELS['summary']}\n\n{normalize_latex(section_summary)}")

        return SECTION_SEPARATOR.join(parts) if parts else ""

    @staticmethod
    def get_teaching_principles() -> str:
        """Return the core teaching principles for reference."""
        return """
## Feynman Teaching Principles

1. **Intuition First** — Start with what the student can visualize,
   then formalize. Never define before explaining WHY.

2. **Plain Language** — If you can't explain it to a bright
   high-schooler, you don't understand it well enough.

3. **Concrete Before Abstract** — Every abstract concept needs
   a concrete anchor (example, analogy, or diagram).

4. **Build Bridges** — Connect new knowledge to what the student
   already knows. Learning is linking.

5. **Check Understanding** — Ask questions to verify comprehension.
   The student should be able to re-explain in their own words.
""".strip()
